name: Playwright Smoke Tests

on:
  schedule:
    - cron: "30 3 * * *" # daily at 6 AM UTC
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright smoke tests with HTML + JSON report
        run: |
          mkdir -p reports
          npx playwright test --grep @smoke --reporter=json,html
          mv playwright-report "reports/$(date +'%Y-%m-%d_%H-%M-%S')"

      - name: Deploy Playwright reports to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reports
          publish_branch: gh-pages
          keep_files: true  # keep older reports instead of deleting them

      - name: Parse results and send summary to Teams
        run: |
          summary=$(jq -r '
            .suites[].specs[] | 
            .title + " → " + (.tests[0].results[0].status)
          ' reports/*/results.json | sed ':a;N;$!ba;s/\n/\\n/g')

          latest_url="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/$(ls -t reports | head -n1)/"

          curl -H 'Content-Type: application/json' \
            -d "{\"text\": \"🧪 Playwright Smoke Test Report\n$summary\n\n📑 [View Latest Report]($latest_url)\"}" \
            ${{ secrets.TEAMS_WEBHOOK_URL }}
